### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by imrohitkumar**
Add 64bit support

### CODE REVIEW

**Comment by otakuhqz** [comment]
@imrohitkumar I think that the pull request #29 is the same as this but more complete, right?

**Comment by imrohitkumar** [comment]
Yes

**Comment by imrohitkumar** [comment]
> @imrohitkumar I think that the pull request #29 is the same as this but more complete, right?

Yes

**Comment by otakuhqz** [comment]
repetido en #29

**Pull request closed without merging**
